name: cron daily update
on:
  workflow_dispatch:
  schedule:
    # 0:02 PST and 1:02 PDT
    - cron: 2 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Revalidate
        run: |
          curl --location --request POST 'https://slug.napatsc.com/api/revalidate' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "SECRET": ${{secrets.SECRET}}
          }'
