name: cron daily update
on:
  schedule:
    # 0:02 PST and 1:02 PDT
    - cron: 2 8 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Revalidate
        run: |
          curl --request POST \
            --url https://slug.napatsc.com/api/revalidate \
            --header 'content-type: application/json' \
            --data '{"SECRET": secrets.SECRET}'
